### ISSUE TITLE
Frontend Error and Warning messages

### ISSUE THREAD

**Issue by pizzalemon** [tj-uav/GroundStation#50] opened 2021-11-13 20:52 UTC
Error and warning messages are a useful interface tool for letting the user know an error has happened, or to warn the user about whatever they're doing (such as editing ODLC submissions, which would decrease our score in AUVSI SUAS). I envision that these would be some sort of popup which fades away after a few seconds, preferably in the bottom left of the screen. It should not obscure the flight map.
While there is a 'console' on the flight data page, it is not on every page, so it may not be a good idea to use that for error messages.

**Comment by krishnans2006** [comment] 2023-02-10 00:44
Duplicate of #97

**Closed as not planned by krishnans2006** 2023-02-10 00:44 UTC
Labels: type/feat, area/frontend
